name: Update Market Prices

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Tracker Script
        env:
          REBRICKABLE_KEY: ${{ secrets.REBRICKABLE_KEY }}
        run: python tracker.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json diecast.json
          git commit -m "Update Market Prices: LEGO & Elite Diecast" || exit 0
          git push
